server:
  service_name: user
  http:
    addr: 127.0.0.1
    port: 8001
    timeout: 6s
  grpc:
    addr: 127.0.0.1
    port: 9001
    timeout: 6s
data:
  database:
    driver: mysql
    source: wsdev:8yovNFYOIsKXw*M5@tcp(10.204.0.16:3306)/ws_dev_boss_db?multiStatements=true
  redis:
    addr: 10.204.0.3:6379
    user: ""
    pwd: "Efwm5k3OfRFXe@Jyb3"
    db: 0
    read_timeout: 10s
    write_timeout: 10s
